### ISSUE TITLE
How can I run this sample?

### ISSUE THREAD

**Issue by guoguoguilai** [rewk09/Multi-User-VR#1]
Unity:2018.3.10f1
When I open this scene, it just throws a thousand errors: TargetParameterCountException: Number of parameters specified does not match the expected number.

**Comment by amit-ghimire** [comment]
Hey sorry I had not noticed your issue. Did it work? Might be an issue with unity or assets versioning conflict.

**Comment by amit-ghimire** [comment]
Working with Unity 2019.4, SteamVR220, VRTK 330.
Follow the instructions [here](https://github.com/WildStyle69/SteamVR_Unity_Toolkit/tree/feat/steamvr2-input-system).
